-- MySQL Script generated by MySQL Workbench
-- 02/22/16 15:41:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cinema` DEFAULT CHARACTER SET utf8 ;
USE `Cinema` ;

-- -----------------------------------------------------
-- Table `Cinema`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `bonus_count` INT NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`films` (
  `id_film` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `director` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `age_limitation` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `poster` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_film`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`halls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`halls` (
  `id_hall` INT NOT NULL AUTO_INCREMENT,
  `format` VARCHAR(45) NOT NULL,
  `capicity` INT NOT NULL,
  PRIMARY KEY (`id_hall`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`session` (
  `id_session` INT NOT NULL AUTO_INCREMENT,
  `id_hall` INT NOT NULL,
  `id_film` INT NOT NULL,
  `date` DATE NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_session`),
  INDEX `id_hall_idx` (`id_hall` ASC),
  INDEX `id_film_idx` (`id_film` ASC),
  CONSTRAINT `id_hall`
    FOREIGN KEY (`id_hall`)
    REFERENCES `Cinema`.`halls` (`id_hall`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_film`
    FOREIGN KEY (`id_film`)
    REFERENCES `Cinema`.`films` (`id_film`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`payticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`payticket` (
  `id_payticket` INT NOT NULL AUTO_INCREMENT,
  `id_ticket` INT NOT NULL,
  `id_user` INT NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `system` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_payticket`),
  INDEX `id_ticket_idx` (`id_ticket` ASC),
  INDEX `id_user_idx` (`id_user` ASC),
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `Cinema`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_ticket`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `Cinema`.`tickets` (`id_ticket`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`tickets` (
  `id_ticket` INT NOT NULL AUTO_INCREMENT,
  `price` INT NOT NULL,
  `id_session` INT NOT NULL,
  `bonus_code` VARCHAR(45) NOT NULL,
  `id_payticket` INT NOT NULL,
  PRIMARY KEY (`id_ticket`),
  INDEX `id_session_idx` (`id_session` ASC),
  INDEX `id_payticket_idx` (`id_payticket` ASC),
  CONSTRAINT `id_session`
    FOREIGN KEY (`id_session`)
    REFERENCES `Cinema`.`session` (`id_session`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_payticket`
    FOREIGN KEY (`id_payticket`)
    REFERENCES `Cinema`.`payticket` (`id_payticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`employees` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `post` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`payticket_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`payticket_messages` (
  `id_payticket_message` INT NOT NULL AUTO_INCREMENT,
  `id_payticket` INT NOT NULL,
  `id_employee` INT NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_payticket_message`),
  INDEX `id_employee_idx` (`id_employee` ASC),
  INDEX `id_payticket_idx` (`id_payticket` ASC),
  CONSTRAINT `id_employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `Cinema`.`employees` (`id_employee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_payticket`
    FOREIGN KEY (`id_payticket`)
    REFERENCES `Cinema`.`payticket` (`id_payticket`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`session_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`session_messages` (
  `id_session_messages` INT NOT NULL AUTO_INCREMENT,
  `id_session` INT NOT NULL,
  `id_emplooyee` INT NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_session_messages`),
  INDEX `id_employee_idx` (`id_emplooyee` ASC),
  INDEX `id_session_idx` (`id_session` ASC),
  CONSTRAINT `id_employee`
    FOREIGN KEY (`id_emplooyee`)
    REFERENCES `Cinema`.`employees` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_session`
    FOREIGN KEY (`id_session`)
    REFERENCES `Cinema`.`session` (`id_session`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`users_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`users_messages` (
  `id_users_messages` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_employee` INT NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_users_messages`),
  INDEX `id_employee_idx` (`id_employee` ASC),
  INDEX `id_user_idx` (`id_user` ASC),
  CONSTRAINT `id_employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `Cinema`.`employees` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `Cinema`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
